name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag UPchieve-server:$(date +%s) 
    - name: authenticate
      run: docker login docker.pkg.github.com -u 
